Started analysis of HER21_R1.fastq.gz
Approx 5% complete for HER21_R1.fastq.gz
Approx 10% complete for HER21_R1.fastq.gz
Approx 15% complete for HER21_R1.fastq.gz
Approx 20% complete for HER21_R1.fastq.gz
Approx 25% complete for HER21_R1.fastq.gz
Approx 30% complete for HER21_R1.fastq.gz
Approx 35% complete for HER21_R1.fastq.gz
Approx 40% complete for HER21_R1.fastq.gz
Approx 45% complete for HER21_R1.fastq.gz
Approx 50% complete for HER21_R1.fastq.gz
Approx 55% complete for HER21_R1.fastq.gz
Approx 60% complete for HER21_R1.fastq.gz
Approx 65% complete for HER21_R1.fastq.gz
Approx 70% complete for HER21_R1.fastq.gz
Approx 75% complete for HER21_R1.fastq.gz
Approx 80% complete for HER21_R1.fastq.gz
Approx 85% complete for HER21_R1.fastq.gz
Approx 90% complete for HER21_R1.fastq.gz
Approx 95% complete for HER21_R1.fastq.gz
Started analysis of HER21_R2.fastq.gz
Approx 5% complete for HER21_R2.fastq.gz
Approx 10% complete for HER21_R2.fastq.gz
Approx 15% complete for HER21_R2.fastq.gz
Approx 20% complete for HER21_R2.fastq.gz
Approx 25% complete for HER21_R2.fastq.gz
Approx 30% complete for HER21_R2.fastq.gz
Approx 35% complete for HER21_R2.fastq.gz
Approx 40% complete for HER21_R2.fastq.gz
Approx 45% complete for HER21_R2.fastq.gz
Approx 50% complete for HER21_R2.fastq.gz
Approx 55% complete for HER21_R2.fastq.gz
Approx 60% complete for HER21_R2.fastq.gz
Approx 65% complete for HER21_R2.fastq.gz
Approx 70% complete for HER21_R2.fastq.gz
Approx 75% complete for HER21_R2.fastq.gz
Approx 80% complete for HER21_R2.fastq.gz
Approx 85% complete for HER21_R2.fastq.gz
Approx 90% complete for HER21_R2.fastq.gz
Approx 95% complete for HER21_R2.fastq.gz
Started analysis of HER22_R1.fastq.gz
Approx 5% complete for HER22_R1.fastq.gz
Approx 10% complete for HER22_R1.fastq.gz
Approx 15% complete for HER22_R1.fastq.gz
Approx 20% complete for HER22_R1.fastq.gz
Approx 25% complete for HER22_R1.fastq.gz
Approx 30% complete for HER22_R1.fastq.gz
Approx 35% complete for HER22_R1.fastq.gz
Approx 40% complete for HER22_R1.fastq.gz
Approx 45% complete for HER22_R1.fastq.gz
Approx 50% complete for HER22_R1.fastq.gz
Approx 55% complete for HER22_R1.fastq.gz
Approx 60% complete for HER22_R1.fastq.gz
Approx 65% complete for HER22_R1.fastq.gz
Approx 70% complete for HER22_R1.fastq.gz
Approx 75% complete for HER22_R1.fastq.gz
Approx 80% complete for HER22_R1.fastq.gz
Approx 85% complete for HER22_R1.fastq.gz
Approx 90% complete for HER22_R1.fastq.gz
Approx 95% complete for HER22_R1.fastq.gz
Started analysis of HER22_R2.fastq.gz
Approx 5% complete for HER22_R2.fastq.gz
Approx 10% complete for HER22_R2.fastq.gz
Approx 15% complete for HER22_R2.fastq.gz
Approx 20% complete for HER22_R2.fastq.gz
Approx 25% complete for HER22_R2.fastq.gz
Approx 30% complete for HER22_R2.fastq.gz
Approx 35% complete for HER22_R2.fastq.gz
Approx 40% complete for HER22_R2.fastq.gz
Approx 45% complete for HER22_R2.fastq.gz
Approx 50% complete for HER22_R2.fastq.gz
Approx 55% complete for HER22_R2.fastq.gz
Approx 60% complete for HER22_R2.fastq.gz
Approx 65% complete for HER22_R2.fastq.gz
Approx 70% complete for HER22_R2.fastq.gz
Approx 75% complete for HER22_R2.fastq.gz
Approx 80% complete for HER22_R2.fastq.gz
Approx 85% complete for HER22_R2.fastq.gz
Approx 90% complete for HER22_R2.fastq.gz
Approx 95% complete for HER22_R2.fastq.gz
Started analysis of HER23_R1.fastq.gz
Approx 5% complete for HER23_R1.fastq.gz
Approx 10% complete for HER23_R1.fastq.gz
Approx 15% complete for HER23_R1.fastq.gz
Approx 20% complete for HER23_R1.fastq.gz
Approx 25% complete for HER23_R1.fastq.gz
Approx 30% complete for HER23_R1.fastq.gz
Approx 35% complete for HER23_R1.fastq.gz
Approx 40% complete for HER23_R1.fastq.gz
Approx 45% complete for HER23_R1.fastq.gz
Approx 50% complete for HER23_R1.fastq.gz
Approx 55% complete for HER23_R1.fastq.gz
Approx 60% complete for HER23_R1.fastq.gz
Approx 65% complete for HER23_R1.fastq.gz
Approx 70% complete for HER23_R1.fastq.gz
Approx 75% complete for HER23_R1.fastq.gz
Approx 80% complete for HER23_R1.fastq.gz
Approx 85% complete for HER23_R1.fastq.gz
Approx 90% complete for HER23_R1.fastq.gz
Approx 95% complete for HER23_R1.fastq.gz
Started analysis of HER23_R2.fastq.gz
Approx 5% complete for HER23_R2.fastq.gz
Approx 10% complete for HER23_R2.fastq.gz
Approx 15% complete for HER23_R2.fastq.gz
Approx 20% complete for HER23_R2.fastq.gz
Approx 25% complete for HER23_R2.fastq.gz
Approx 30% complete for HER23_R2.fastq.gz
Approx 35% complete for HER23_R2.fastq.gz
Approx 40% complete for HER23_R2.fastq.gz
Approx 45% complete for HER23_R2.fastq.gz
Approx 50% complete for HER23_R2.fastq.gz
Approx 55% complete for HER23_R2.fastq.gz
Approx 60% complete for HER23_R2.fastq.gz
Approx 65% complete for HER23_R2.fastq.gz
Approx 70% complete for HER23_R2.fastq.gz
Approx 75% complete for HER23_R2.fastq.gz
Approx 80% complete for HER23_R2.fastq.gz
Approx 85% complete for HER23_R2.fastq.gz
Approx 90% complete for HER23_R2.fastq.gz
Approx 95% complete for HER23_R2.fastq.gz
Started analysis of NonTNBC1_R1.fastq.gz
Approx 5% complete for NonTNBC1_R1.fastq.gz
Approx 10% complete for NonTNBC1_R1.fastq.gz
Approx 15% complete for NonTNBC1_R1.fastq.gz
Approx 20% complete for NonTNBC1_R1.fastq.gz
Approx 25% complete for NonTNBC1_R1.fastq.gz
Approx 30% complete for NonTNBC1_R1.fastq.gz
Approx 35% complete for NonTNBC1_R1.fastq.gz
Approx 40% complete for NonTNBC1_R1.fastq.gz
Approx 45% complete for NonTNBC1_R1.fastq.gz
Approx 50% complete for NonTNBC1_R1.fastq.gz
Approx 55% complete for NonTNBC1_R1.fastq.gz
Approx 60% complete for NonTNBC1_R1.fastq.gz
Approx 65% complete for NonTNBC1_R1.fastq.gz
Approx 70% complete for NonTNBC1_R1.fastq.gz
Approx 75% complete for NonTNBC1_R1.fastq.gz
Approx 80% complete for NonTNBC1_R1.fastq.gz
Approx 85% complete for NonTNBC1_R1.fastq.gz
Approx 90% complete for NonTNBC1_R1.fastq.gz
Approx 95% complete for NonTNBC1_R1.fastq.gz
Started analysis of NonTNBC1_R2.fastq.gz
Approx 5% complete for NonTNBC1_R2.fastq.gz
Approx 10% complete for NonTNBC1_R2.fastq.gz
Approx 15% complete for NonTNBC1_R2.fastq.gz
Approx 20% complete for NonTNBC1_R2.fastq.gz
Approx 25% complete for NonTNBC1_R2.fastq.gz
Approx 30% complete for NonTNBC1_R2.fastq.gz
Approx 35% complete for NonTNBC1_R2.fastq.gz
Approx 40% complete for NonTNBC1_R2.fastq.gz
Approx 45% complete for NonTNBC1_R2.fastq.gz
Approx 50% complete for NonTNBC1_R2.fastq.gz
Approx 55% complete for NonTNBC1_R2.fastq.gz
Approx 60% complete for NonTNBC1_R2.fastq.gz
Approx 65% complete for NonTNBC1_R2.fastq.gz
Approx 70% complete for NonTNBC1_R2.fastq.gz
Approx 75% complete for NonTNBC1_R2.fastq.gz
Approx 80% complete for NonTNBC1_R2.fastq.gz
Approx 85% complete for NonTNBC1_R2.fastq.gz
Approx 90% complete for NonTNBC1_R2.fastq.gz
Approx 95% complete for NonTNBC1_R2.fastq.gz
Started analysis of NonTNBC2_R1.fastq.gz
Approx 5% complete for NonTNBC2_R1.fastq.gz
Approx 10% complete for NonTNBC2_R1.fastq.gz
Approx 15% complete for NonTNBC2_R1.fastq.gz
Approx 20% complete for NonTNBC2_R1.fastq.gz
Approx 25% complete for NonTNBC2_R1.fastq.gz
Approx 30% complete for NonTNBC2_R1.fastq.gz
Approx 35% complete for NonTNBC2_R1.fastq.gz
Approx 40% complete for NonTNBC2_R1.fastq.gz
Approx 45% complete for NonTNBC2_R1.fastq.gz
Approx 50% complete for NonTNBC2_R1.fastq.gz
Approx 55% complete for NonTNBC2_R1.fastq.gz
Approx 60% complete for NonTNBC2_R1.fastq.gz
Approx 65% complete for NonTNBC2_R1.fastq.gz
Approx 70% complete for NonTNBC2_R1.fastq.gz
Approx 75% complete for NonTNBC2_R1.fastq.gz
Approx 80% complete for NonTNBC2_R1.fastq.gz
Approx 85% complete for NonTNBC2_R1.fastq.gz
Approx 90% complete for NonTNBC2_R1.fastq.gz
Approx 95% complete for NonTNBC2_R1.fastq.gz
Started analysis of NonTNBC2_R2.fastq.gz
Approx 5% complete for NonTNBC2_R2.fastq.gz
Approx 10% complete for NonTNBC2_R2.fastq.gz
Approx 15% complete for NonTNBC2_R2.fastq.gz
Approx 20% complete for NonTNBC2_R2.fastq.gz
Approx 25% complete for NonTNBC2_R2.fastq.gz
Approx 30% complete for NonTNBC2_R2.fastq.gz
Approx 35% complete for NonTNBC2_R2.fastq.gz
Approx 40% complete for NonTNBC2_R2.fastq.gz
Approx 45% complete for NonTNBC2_R2.fastq.gz
Approx 50% complete for NonTNBC2_R2.fastq.gz
Approx 55% complete for NonTNBC2_R2.fastq.gz
Approx 60% complete for NonTNBC2_R2.fastq.gz
Approx 65% complete for NonTNBC2_R2.fastq.gz
Approx 70% complete for NonTNBC2_R2.fastq.gz
Approx 75% complete for NonTNBC2_R2.fastq.gz
Approx 80% complete for NonTNBC2_R2.fastq.gz
Approx 85% complete for NonTNBC2_R2.fastq.gz
Approx 90% complete for NonTNBC2_R2.fastq.gz
Approx 95% complete for NonTNBC2_R2.fastq.gz
Started analysis of NonTNBC3_R1.fastq.gz
Approx 5% complete for NonTNBC3_R1.fastq.gz
Approx 10% complete for NonTNBC3_R1.fastq.gz
Approx 15% complete for NonTNBC3_R1.fastq.gz
Approx 20% complete for NonTNBC3_R1.fastq.gz
Approx 25% complete for NonTNBC3_R1.fastq.gz
Approx 30% complete for NonTNBC3_R1.fastq.gz
Approx 35% complete for NonTNBC3_R1.fastq.gz
Approx 40% complete for NonTNBC3_R1.fastq.gz
Approx 45% complete for NonTNBC3_R1.fastq.gz
Approx 50% complete for NonTNBC3_R1.fastq.gz
Approx 55% complete for NonTNBC3_R1.fastq.gz
Approx 60% complete for NonTNBC3_R1.fastq.gz
Approx 65% complete for NonTNBC3_R1.fastq.gz
Approx 70% complete for NonTNBC3_R1.fastq.gz
Approx 75% complete for NonTNBC3_R1.fastq.gz
Approx 80% complete for NonTNBC3_R1.fastq.gz
Approx 85% complete for NonTNBC3_R1.fastq.gz
Approx 90% complete for NonTNBC3_R1.fastq.gz
Approx 95% complete for NonTNBC3_R1.fastq.gz
Started analysis of NonTNBC3_R2.fastq.gz
Approx 5% complete for NonTNBC3_R2.fastq.gz
Approx 10% complete for NonTNBC3_R2.fastq.gz
Approx 15% complete for NonTNBC3_R2.fastq.gz
Approx 20% complete for NonTNBC3_R2.fastq.gz
Approx 25% complete for NonTNBC3_R2.fastq.gz
Approx 30% complete for NonTNBC3_R2.fastq.gz
Approx 35% complete for NonTNBC3_R2.fastq.gz
Approx 40% complete for NonTNBC3_R2.fastq.gz
Approx 45% complete for NonTNBC3_R2.fastq.gz
Approx 50% complete for NonTNBC3_R2.fastq.gz
Approx 55% complete for NonTNBC3_R2.fastq.gz
Approx 60% complete for NonTNBC3_R2.fastq.gz
Approx 65% complete for NonTNBC3_R2.fastq.gz
Approx 70% complete for NonTNBC3_R2.fastq.gz
Approx 75% complete for NonTNBC3_R2.fastq.gz
Approx 80% complete for NonTNBC3_R2.fastq.gz
Approx 85% complete for NonTNBC3_R2.fastq.gz
Approx 90% complete for NonTNBC3_R2.fastq.gz
Approx 95% complete for NonTNBC3_R2.fastq.gz
Started analysis of Normal1_R1.fastq.gz
Approx 5% complete for Normal1_R1.fastq.gz
Approx 10% complete for Normal1_R1.fastq.gz
Approx 15% complete for Normal1_R1.fastq.gz
Approx 20% complete for Normal1_R1.fastq.gz
Approx 25% complete for Normal1_R1.fastq.gz
Approx 30% complete for Normal1_R1.fastq.gz
Approx 35% complete for Normal1_R1.fastq.gz
Approx 40% complete for Normal1_R1.fastq.gz
Approx 45% complete for Normal1_R1.fastq.gz
Approx 50% complete for Normal1_R1.fastq.gz
Approx 55% complete for Normal1_R1.fastq.gz
Approx 60% complete for Normal1_R1.fastq.gz
Approx 65% complete for Normal1_R1.fastq.gz
Approx 70% complete for Normal1_R1.fastq.gz
Approx 75% complete for Normal1_R1.fastq.gz
Approx 80% complete for Normal1_R1.fastq.gz
Approx 85% complete for Normal1_R1.fastq.gz
Approx 90% complete for Normal1_R1.fastq.gz
Approx 95% complete for Normal1_R1.fastq.gz
Started analysis of Normal1_R2.fastq.gz
Approx 5% complete for Normal1_R2.fastq.gz
Approx 10% complete for Normal1_R2.fastq.gz
Approx 15% complete for Normal1_R2.fastq.gz
Approx 20% complete for Normal1_R2.fastq.gz
Approx 25% complete for Normal1_R2.fastq.gz
Approx 30% complete for Normal1_R2.fastq.gz
Approx 35% complete for Normal1_R2.fastq.gz
Approx 40% complete for Normal1_R2.fastq.gz
Approx 45% complete for Normal1_R2.fastq.gz
Approx 50% complete for Normal1_R2.fastq.gz
Approx 55% complete for Normal1_R2.fastq.gz
Approx 60% complete for Normal1_R2.fastq.gz
Approx 65% complete for Normal1_R2.fastq.gz
Approx 70% complete for Normal1_R2.fastq.gz
Approx 75% complete for Normal1_R2.fastq.gz
Approx 80% complete for Normal1_R2.fastq.gz
Approx 85% complete for Normal1_R2.fastq.gz
Approx 90% complete for Normal1_R2.fastq.gz
Approx 95% complete for Normal1_R2.fastq.gz
Started analysis of Normal2_R1.fastq.gz
Approx 5% complete for Normal2_R1.fastq.gz
Approx 10% complete for Normal2_R1.fastq.gz
Approx 15% complete for Normal2_R1.fastq.gz
Approx 20% complete for Normal2_R1.fastq.gz
Approx 25% complete for Normal2_R1.fastq.gz
Approx 30% complete for Normal2_R1.fastq.gz
Approx 35% complete for Normal2_R1.fastq.gz
Approx 40% complete for Normal2_R1.fastq.gz
Approx 45% complete for Normal2_R1.fastq.gz
Approx 50% complete for Normal2_R1.fastq.gz
Approx 55% complete for Normal2_R1.fastq.gz
Approx 60% complete for Normal2_R1.fastq.gz
Approx 65% complete for Normal2_R1.fastq.gz
Approx 70% complete for Normal2_R1.fastq.gz
Approx 75% complete for Normal2_R1.fastq.gz
Approx 80% complete for Normal2_R1.fastq.gz
Approx 85% complete for Normal2_R1.fastq.gz
Approx 90% complete for Normal2_R1.fastq.gz
Approx 95% complete for Normal2_R1.fastq.gz
Started analysis of Normal2_R2.fastq.gz
Approx 5% complete for Normal2_R2.fastq.gz
Approx 10% complete for Normal2_R2.fastq.gz
Approx 15% complete for Normal2_R2.fastq.gz
Approx 20% complete for Normal2_R2.fastq.gz
Approx 25% complete for Normal2_R2.fastq.gz
Approx 30% complete for Normal2_R2.fastq.gz
Approx 35% complete for Normal2_R2.fastq.gz
Approx 40% complete for Normal2_R2.fastq.gz
Approx 45% complete for Normal2_R2.fastq.gz
Approx 50% complete for Normal2_R2.fastq.gz
Approx 55% complete for Normal2_R2.fastq.gz
Approx 60% complete for Normal2_R2.fastq.gz
Approx 65% complete for Normal2_R2.fastq.gz
Approx 70% complete for Normal2_R2.fastq.gz
Approx 75% complete for Normal2_R2.fastq.gz
Approx 80% complete for Normal2_R2.fastq.gz
Approx 85% complete for Normal2_R2.fastq.gz
Approx 90% complete for Normal2_R2.fastq.gz
Approx 95% complete for Normal2_R2.fastq.gz
Started analysis of Normal3_R1.fastq.gz
Approx 5% complete for Normal3_R1.fastq.gz
Approx 10% complete for Normal3_R1.fastq.gz
Approx 15% complete for Normal3_R1.fastq.gz
Approx 20% complete for Normal3_R1.fastq.gz
Approx 25% complete for Normal3_R1.fastq.gz
Approx 30% complete for Normal3_R1.fastq.gz
Approx 35% complete for Normal3_R1.fastq.gz
Approx 40% complete for Normal3_R1.fastq.gz
Approx 45% complete for Normal3_R1.fastq.gz
Approx 50% complete for Normal3_R1.fastq.gz
Approx 55% complete for Normal3_R1.fastq.gz
Approx 60% complete for Normal3_R1.fastq.gz
Approx 65% complete for Normal3_R1.fastq.gz
Approx 70% complete for Normal3_R1.fastq.gz
Approx 75% complete for Normal3_R1.fastq.gz
Approx 80% complete for Normal3_R1.fastq.gz
Approx 85% complete for Normal3_R1.fastq.gz
Approx 90% complete for Normal3_R1.fastq.gz
Approx 95% complete for Normal3_R1.fastq.gz
Started analysis of Normal3_R2.fastq.gz
Approx 5% complete for Normal3_R2.fastq.gz
Approx 10% complete for Normal3_R2.fastq.gz
Approx 15% complete for Normal3_R2.fastq.gz
Approx 20% complete for Normal3_R2.fastq.gz
Approx 25% complete for Normal3_R2.fastq.gz
Approx 30% complete for Normal3_R2.fastq.gz
Approx 35% complete for Normal3_R2.fastq.gz
Approx 40% complete for Normal3_R2.fastq.gz
Approx 45% complete for Normal3_R2.fastq.gz
Approx 50% complete for Normal3_R2.fastq.gz
Approx 55% complete for Normal3_R2.fastq.gz
Approx 60% complete for Normal3_R2.fastq.gz
Approx 65% complete for Normal3_R2.fastq.gz
Approx 70% complete for Normal3_R2.fastq.gz
Approx 75% complete for Normal3_R2.fastq.gz
